//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uPPERaTIVE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnicalIssues
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string IssueDescription { get; set; }
        public string OperatorId { get; set; }
    }
}
