//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uPPERaTIVE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.ClientOperatorChat = new HashSet<ClientOperatorChat>();
            this.IssueAcceptance = new HashSet<IssueAcceptance>();
        }
    
        public int id { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Login { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public Nullable<int> IssueId { get; set; }
        public Nullable<int> QualId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientOperatorChat> ClientOperatorChat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueAcceptance> IssueAcceptance { get; set; }
        public virtual IssueQualification IssueQualification { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
